# -*- coding: utf-8 -*-
"""gdp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQvOMPaQCpbWOCB3CvZzsqeDDHslYOHQ
"""

import re
from io import StringIO

import pandas as pd
import plotly.express as px
import requests
import streamlit as st
import country_converter as coco

st.set_page_config(page_title="GDP by Region", layout="wide")
st.title("GDP by Region")
st.write("Country GDPs are stacked within regions. Use the dropdown to switch between IMF, UN, and World Bank data.")

URL = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

NAME_FIXES = {
    "Türkiye": "Turkey",
    "Czech Republic": "Czechia",
    "Republic of the Congo": "Congo Republic",
    "Democratic Republic of the Congo": "DR Congo",
    "Ivory Coast": "Côte d'Ivoire",
    "South Korea": "Korea, Republic of",
    "North Korea": "Korea, Democratic People's Republic of",
    "Russia": "Russian Federation",
    "Syria": "Syrian Arab Republic",
    "Iran": "Iran, Islamic Republic of",
    "Moldova": "Moldova, Republic of",
    "Venezuela": "Venezuela, Bolivarian Republic of",
    "Laos": "Lao People's Democratic Republic",
    "Brunei": "Brunei Darussalam",
    "Cape Verde": "Cabo Verde",
    "Swaziland": "Eswatini",
    "Micronesia": "Micronesia, Federated States of",
    "Bahamas": "Bahamas, The",
    "Gambia": "Gambia, The",
    "East Timor": "Timor-Leste",
    "Macao": "Macau"
}

REGION_FIXES = {
    "Taiwan": "Asia",
    "Hong Kong": "Asia",
    "Macau": "Asia",
    "Kosovo": "Europe",
    "Palestine": "Asia"
}


def flatten_columns(columns):
    new_cols = []
    for col in columns:
        if isinstance(col, tuple):
            parts = [
                str(x).strip()
                for x in col
                if str(x) != "nan" and not str(x).startswith("Unnamed")
            ]
            new_cols.append(" ".join(parts))
        else:
            new_cols.append(str(col))
    return new_cols


def pick_value_column(columns, source_keyword):
    candidates = [c for c in columns if source_keyword in c.lower()]
    preferred = [
        c for c in candidates
        if ("forecast" in c.lower() or "estimate" in c.lower()) and "year" not in c.lower()
    ]
    if preferred:
        return preferred[0]
    for c in candidates:
        if "year" not in c.lower():
            return c
    raise ValueError(f"Could not find value column for {source_keyword}")


def clean_number(x):
    if pd.isna(x):
        return pd.NA
    s = str(x)
    s = re.sub(r"\[[^\]]*\]", "", s)
    s = s.replace(",", "").replace("—", "").replace("–", "").replace("−", "").strip()
    if s in {"", "N/A", "NA"}:
        return pd.NA
    s = re.sub(r"[^\d.]", "", s)
    return float(s) if s else pd.NA


def get_region(country_name):
    if pd.isna(country_name):
        return None

    country_name = str(country_name).strip()

    if country_name in REGION_FIXES:
        return REGION_FIXES[country_name]

    converted_name = NAME_FIXES.get(country_name, country_name)
    region = coco.convert(names=converted_name, to="continent")

    if region in {"not found", "", None}:
        return None

    return region


@st.cache_data
def load_gdp_data():
    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(URL, headers=headers, timeout=30)
    response.raise_for_status()

    tables = pd.read_html(StringIO(response.text))

    gdp_table = None
    for table in tables:
        table = table.copy()
        table.columns = flatten_columns(table.columns)
        joined = " | ".join(c.lower() for c in table.columns)

        if "country" in joined and "imf" in joined and "world bank" in joined and "united nations" in joined:
            gdp_table = table
            break

    if gdp_table is None:
        raise ValueError("Could not find the GDP table on the page.")

    country_col = next(c for c in gdp_table.columns if "country" in c.lower())
    imf_col = pick_value_column(gdp_table.columns, "imf")
    wb_col = pick_value_column(gdp_table.columns, "world bank")
    un_col = pick_value_column(gdp_table.columns, "united nations")

    df = gdp_table[[country_col, imf_col, wb_col, un_col]].copy()
    df.columns = ["Country", "IMF", "World Bank", "UN"]

    df["Country"] = df["Country"].astype(str).str.replace(r"\[.*?\]", "", regex=True).str.strip()

    for col in ["IMF", "World Bank", "UN"]:
        df[col] = df[col].apply(clean_number)

    df["Region"] = df["Country"].apply(get_region)
    df = df[df["Region"].notna()].copy()

    return df


df = load_gdp_data()

source = st.selectbox("Choose GDP source:", ["IMF", "UN", "World Bank"])
top_n = st.slider("Show top N countries per region (others grouped together):", 5, 20, 10)

plot_df = df[["Country", "Region", source]].dropna().copy()

plot_df["rank"] = plot_df.groupby("Region")[source].rank(method="first", ascending=False)
plot_df["Country_plot"] = plot_df.apply(
    lambda row: row["Country"] if row["rank"] <= top_n else f"Other ({row['Region']})",
    axis=1
)

plot_df = plot_df.groupby(["Region", "Country_plot"], as_index=False)[source].sum()

region_order = (
    plot_df.groupby("Region")[source]
    .sum()
    .sort_values(ascending=False)
    .index
    .tolist()
)

plot_df["Region"] = pd.Categorical(plot_df["Region"], categories=region_order, ordered=True)
plot_df = plot_df.sort_values(["Region", source], ascending=[True, False])

fig = px.bar(
    plot_df,
    x="Region",
    y=source,
    color="Country_plot",
    title=f"Country GDPs stacked within regions ({source})",
    labels={source: "GDP (millions of US$)", "Country_plot": "Country"}
)

fig.update_layout(
    barmode="stack",
    xaxis_title="Region",
    yaxis_title="GDP (millions of US$)",
    legend_title="Country",
    height=700
)

st.plotly_chart(fig, use_container_width=True)

with st.expander("Show data used in the chart"):
    st.dataframe(plot_df, use_container_width=True)
